"""empty message

Revision ID: 0b010f3a13bc
Revises: edcaed6d4130
Create Date: 2026-02-17 14:58:53.413798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b010f3a13bc'
down_revision: Union[str, Sequence[str], None] = 'edcaed6d4130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('yookassa_refund_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['user_payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_refunds_payment_id'), 'user_refunds', ['payment_id'], unique=False)
    op.create_index(op.f('ix_user_refunds_yookassa_refund_id'), 'user_refunds', ['yookassa_refund_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_refunds_yookassa_refund_id'), table_name='user_refunds')
    op.drop_index(op.f('ix_user_refunds_payment_id'), table_name='user_refunds')
    op.drop_table('user_refunds')
    # ### end Alembic commands ###
