"""empty message

Revision ID: 13908b8ef0bc
Revises: 0659dadd87b0
Create Date: 2026-02-20 15:44:51.482418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13908b8ef0bc'
down_revision: Union[str, Sequence[str], None] = '0659dadd87b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seller_registration_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=1000), nullable=True),
    sa.Column('short_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('is_IP', sa.Boolean(), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'rejected', 'approved')", name='ck_seller_registration_request_status_valid'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_registration_requests_user_id'), 'seller_registration_requests', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seller_registration_requests_user_id'), table_name='seller_registration_requests')
    op.drop_table('seller_registration_requests')
    # ### end Alembic commands ###