"""empty message

Revision ID: 1b0a63c5bdc0
Revises: f6bf081a953e
Create Date: 2025-12-08 16:49:20.263317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b0a63c5bdc0'
down_revision: Union[str, Sequence[str], None] = 'f6bf081a953e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('firebase_token', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'firebase_token')
    # ### end Alembic commands ###
