"""empty message

Revision ID: 24a28a12b54c
Revises: 08ff0b112bed
Create Date: 2025-09-29 15:55:15.673131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a28a12b54c'
down_revision: Union[str, Sequence[str], None] = '08ff0b112bed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('article', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('code', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'code')
    op.drop_column('products', 'article')
    # ### end Alembic commands ###
