"""empty message

Revision ID: 2e59d0fc7fbc
Revises: e520fe4d4a2f
Create Date: 2025-11-23 16:16:07.183391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e59d0fc7fbc'
down_revision: Union[str, Sequence[str], None] = 'e520fe4d4a2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_offers', sa.Column('fulfillment_status', sa.String(length=50), nullable=True))
    op.add_column('purchase_offers', sa.Column('fulfilled_quantity', sa.Integer(), nullable=True))
    op.add_column('purchase_offers', sa.Column('fulfilled_by_seller_id', sa.Integer(), nullable=True))
    op.add_column('purchase_offers', sa.Column('unfulfilled_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_purchase_offers_fulfilled_by_seller_id'), 'purchase_offers', ['fulfilled_by_seller_id'], unique=False)
    op.create_foreign_key(None, 'purchase_offers', 'sellers', ['fulfilled_by_seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_offers', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_offers_fulfilled_by_seller_id'), table_name='purchase_offers')
    op.drop_column('purchase_offers', 'unfulfilled_reason')
    op.drop_column('purchase_offers', 'fulfilled_by_seller_id')
    op.drop_column('purchase_offers', 'fulfilled_quantity')
    op.drop_column('purchase_offers', 'fulfillment_status')
    # ### end Alembic commands ###
