"""empty message

Revision ID: 31ee485dfaee
Revises: 8687b7cbc8a8
Create Date: 2025-11-09 07:50:42.935963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31ee485dfaee'
down_revision: Union[str, Sequence[str], None] = '8687b7cbc8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('reserved_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'reserved_count')
    # ### end Alembic commands ###
