"""empty message

Revision ID: 326e28927fe9
Revises: aa87c2c66d87
Create Date: 2025-11-10 13:14:07.735162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '326e28927fe9'
down_revision: Union[str, Sequence[str], None] = 'aa87c2c66d87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_offer_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('processed_quantity', sa.Integer(), nullable=True),
    sa.Column('available_quantity', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.CheckConstraint("status IN ('success', 'not_found', 'insufficient_quantity', 'expired')", name='ck_purchase_offer_result_status_valid'),
    sa.CheckConstraint('available_quantity IS NULL OR available_quantity >= 0', name='ck_purchase_offer_result_available_quantity_non_negative'),
    sa.CheckConstraint('processed_quantity IS NULL OR processed_quantity >= 0', name='ck_purchase_offer_result_processed_quantity_non_negative'),
    sa.CheckConstraint('requested_quantity > 0', name='ck_purchase_offer_result_requested_quantity_positive'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_offer_results_purchase_id'), 'purchase_offer_results', ['purchase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_offer_results_purchase_id'), table_name='purchase_offer_results')
    op.drop_table('purchase_offer_results')
    # ### end Alembic commands ###
