"""empty message

Revision ID: 3b74b401ffb3
Revises: aa5826aba04c
Create Date: 2025-11-04 17:15:54.685618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b74b401ffb3'
down_revision: Union[str, Sequence[str], None] = 'aa5826aba04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('expires_date', sa.DateTime(), nullable=True),
    sa.Column('original_cost', sa.Double(), nullable=True),
    sa.Column('current_cost', sa.Double(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.CheckConstraint('count IS NULL OR count >= 0', name='ck_offer_count_positive'),
    sa.CheckConstraint('current_cost IS NULL OR current_cost >= 0', name='ck_offer_current_cost_positive'),
    sa.CheckConstraint('original_cost IS NULL OR original_cost >= 0', name='ck_offer_original_cost_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'shop_id', name='uq_offer_product_shop')
    )
    op.create_index(op.f('ix_offers_product_id'), 'offers', ['product_id'], unique=False)
    op.create_index(op.f('ix_offers_shop_id'), 'offers', ['shop_id'], unique=False)
    op.drop_index(op.f('ix_product_entries_product_id'), table_name='product_entries')
    op.drop_index(op.f('ix_product_entries_shop_id'), table_name='product_entries')
    op.drop_table('product_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shop_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expires_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('original_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('count >= 0', name=op.f('ck_product_entry_count_positive')),
    sa.CheckConstraint('current_cost >= 0::double precision', name=op.f('ck_product_entry_current_cost_positive')),
    sa.CheckConstraint('original_cost >= 0::double precision', name=op.f('ck_product_entry_original_cost_positive')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_entries_product_id_fkey')),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_points.id'], name=op.f('product_entries_shop_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_entries_pkey')),
    sa.UniqueConstraint('product_id', 'shop_id', name=op.f('uq_product_entry_product_shop'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_product_entries_shop_id'), 'product_entries', ['shop_id'], unique=False)
    op.create_index(op.f('ix_product_entries_product_id'), 'product_entries', ['product_id'], unique=False)
    op.drop_index(op.f('ix_offers_shop_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_product_id'), table_name='offers')
    op.drop_table('offers')
    # ### end Alembic commands ###
