"""empty message

Revision ID: 635078a0d209
Revises: 23d17a6d0857
Create Date: 2025-10-23 06:28:06.849772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635078a0d209'
down_revision: Union[str, Sequence[str], None] = '23d17a6d0857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('is_IP', sa.Boolean(), nullable=False))
    op.drop_column('sellers', 'org_type')
    op.add_column('users', sa.Column('is_seller', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_seller')
    op.add_column('sellers', sa.Column('org_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('sellers', 'is_IP')
    # ### end Alembic commands ###
