"""empty message

Revision ID: 7f892c7aab42
Revises: 
Create Date: 2025-10-16 15:02:24.027026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f892c7aab42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('length(name) >= 1', name='ck_product_category_name_min_length'),
    sa.CheckConstraint('length(slug) >= 1', name='ck_product_category_slug_min_length'),
    sa.CheckConstraint('parent_category_id IS NULL OR parent_category_id != id', name='ck_product_category_no_self_parent'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sellers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=1000), nullable=False),
    sa.Column('short_name', sa.String(length=255), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('org_type', sa.Integer(), nullable=False),
    sa.Column('ogrn', sa.String(length=15), nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('verification_level', sa.Integer(), nullable=False),
    sa.Column('registration_doc_url', sa.String(length=2048), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('article', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('description IS NULL OR length(description) <= 10000', name='ck_product_description_max_length'),
    sa.CheckConstraint('length(name) >= 1', name='ck_product_name_min_length'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seller_images',
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Double(), nullable=True),
    sa.Column('longitude', sa.Double(), nullable=True),
    sa.CheckConstraint('latitude >= -90 AND latitude <= 90', name='ck_shop_point_latitude_range'),
    sa.CheckConstraint('longitude >= -180 AND longitude <= 180', name='ck_shop_point_longitude_range'),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shop_points_coordinates', 'shop_points', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_shop_points_seller_id'), 'shop_points', ['seller_id'], unique=False)
    op.create_table('product_category_relations',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'product_id')
    )
    op.create_table('product_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.Column('expires_date', sa.DateTime(), nullable=False),
    sa.Column('original_cost', sa.Double(), nullable=False),
    sa.Column('current_cost', sa.Double(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.CheckConstraint('count >= 0', name='ck_product_entry_count_positive'),
    sa.CheckConstraint('current_cost >= 0', name='ck_product_entry_current_cost_positive'),
    sa.CheckConstraint('original_cost >= 0', name='ck_product_entry_original_cost_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['shop_id'], ['shop_points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'shop_id', name='uq_product_entry_product_shop')
    )
    op.create_index(op.f('ix_product_entries_product_id'), 'product_entries', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_entries_shop_id'), 'product_entries', ['shop_id'], unique=False)
    op.create_table('product_images',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop_point_images',
    sa.Column('shop_point_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_point_id'], ['shop_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shop_point_images')
    op.drop_table('product_images')
    op.drop_index(op.f('ix_product_entries_shop_id'), table_name='product_entries')
    op.drop_index(op.f('ix_product_entries_product_id'), table_name='product_entries')
    op.drop_table('product_entries')
    op.drop_table('product_category_relations')
    op.drop_index(op.f('ix_shop_points_seller_id'), table_name='shop_points')
    op.drop_index('ix_shop_points_coordinates', table_name='shop_points')
    op.drop_table('shop_points')
    op.drop_table('seller_images')
    op.drop_table('products')
    op.drop_table('sellers')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
