"""empty message

Revision ID: 8687b7cbc8a8
Revises: 86d2e77402c4
Create Date: 2025-11-04 18:06:08.363156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8687b7cbc8a8'
down_revision: Union[str, Sequence[str], None] = '86d2e77402c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_offer_product_shop'), 'offers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_offer_product_shop'), 'offers', ['product_id', 'shop_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
