"""empty message

Revision ID: 9ed8c0bbb470
Revises: 13908b8ef0bc
Create Date: 2026-03-02 23:09:59.374578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed8c0bbb470'
down_revision: Union[str, Sequence[str], None] = '13908b8ef0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_offer_results', sa.Column('refund_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_purchase_offer_results_refund_id'), 'purchase_offer_results', ['refund_id'], unique=False)
    op.create_foreign_key(None, 'purchase_offer_results', 'user_refunds', ['refund_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'purchase_offer_results', type_='foreignkey')
    op.drop_index(op.f('ix_purchase_offer_results_refund_id'), table_name='purchase_offer_results')
    op.drop_column('purchase_offer_results', 'refund_id')
    # ### end Alembic commands ###