"""empty message

Revision ID: a9b86747eaa8
Revises: f60d8c339243
Create Date: 2025-12-14 03:15:03.730813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b86747eaa8'
down_revision: Union[str, Sequence[str], None] = 'f60d8c339243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offers_pricing_strategy_id'), table_name='offers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_offers_pricing_strategy_id'), 'offers', ['pricing_strategy_id'], unique=False)
    # ### end Alembic commands ###
