"""empty message

Revision ID: aa5826aba04c
Revises: 9833e2cdb5dc
Create Date: 2025-11-04 14:29:47.058050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5826aba04c'
down_revision: Union[str, Sequence[str], None] = '9833e2cdb5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1000), nullable=False),
    sa.CheckConstraint('length(name) >= 1', name='ck_product_attribute_name_min_length'),
    sa.CheckConstraint('length(slug) >= 1', name='ck_product_attribute_slug_min_length'),
    sa.CheckConstraint('length(value) >= 1', name='ck_product_attribute_value_min_length'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'slug', name='uq_product_attribute_product_slug')
    )
    op.create_index(op.f('ix_product_attributes_product_id'), 'product_attributes', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_attributes_product_id'), table_name='product_attributes')
    op.drop_table('product_attributes')
    # ### end Alembic commands ###
