"""empty message

Revision ID: aa87c2c66d87
Revises: 31ee485dfaee
Create Date: 2025-11-09 15:06:02.252707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa87c2c66d87'
down_revision: Union[str, Sequence[str], None] = '31ee485dfaee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('total_cost', sa.Double(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'cancelled', 'completed')", name='ck_purchase_status_valid'),
    sa.CheckConstraint('total_cost IS NULL OR total_cost >= 0', name='ck_purchase_total_cost_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchases_user_id'), 'purchases', ['user_id'], unique=False)
    op.create_table('purchase_offers',
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('cost_at_purchase', sa.Double(), nullable=True),
    sa.CheckConstraint('cost_at_purchase IS NULL OR cost_at_purchase >= 0', name='ck_purchase_offer_cost_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_offer_quantity_positive'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('purchase_id', 'offer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_offers')
    op.drop_index(op.f('ix_purchases_user_id'), table_name='purchases')
    op.drop_table('purchases')
    # ### end Alembic commands ###
