"""empty message

Revision ID: ced920a548ff
Revises: 1b0a63c5bdc0
Create Date: 2025-12-08 20:11:22.893454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced920a548ff'
down_revision: Union[str, Sequence[str], None] = '1b0a63c5bdc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_latitude', sa.Double(), nullable=True, comment='Last known latitude coordinate of the user'))
    op.add_column('users', sa.Column('last_longitude', sa.Double(), nullable=True, comment='Last known longitude coordinate of the user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_longitude')
    op.drop_column('users', 'last_latitude')
    # ### end Alembic commands ###
