"""empty message

Revision ID: e520fe4d4a2f
Revises: b4ea6b713acf
Create Date: 2025-11-15 17:39:53.168909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e520fe4d4a2f'
down_revision: Union[str, Sequence[str], None] = 'b4ea6b713acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('yookassa_payment_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Double(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('confirmation_url', sa.String(length=2048), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('idempotence_key', sa.String(length=255), nullable=True),
    sa.Column('paid_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('captured_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('cancellation_details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint("currency IN ('RUB')", name='ck_user_payment_currency_valid'),
    sa.CheckConstraint("status IN ('pending', 'waiting_for_capture', 'succeeded', 'canceled')", name='ck_user_payment_status_valid'),
    sa.CheckConstraint('amount > 0', name='ck_user_payment_amount_positive'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_payments_idempotence_key'), 'user_payments', ['idempotence_key'], unique=False)
    op.create_index(op.f('ix_user_payments_purchase_id'), 'user_payments', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_user_payments_yookassa_payment_id'), 'user_payments', ['yookassa_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_payments_yookassa_payment_id'), table_name='user_payments')
    op.drop_index(op.f('ix_user_payments_purchase_id'), table_name='user_payments')
    op.drop_index(op.f('ix_user_payments_idempotence_key'), table_name='user_payments')
    op.drop_table('user_payments')
    # ### end Alembic commands ###
