"""empty message

Revision ID: f60d8c339243
Revises: ced920a548ff
Create Date: 2025-12-14 03:12:47.765453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60d8c339243'
down_revision: Union[str, Sequence[str], None] = 'ced920a548ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.CheckConstraint('length(name) >= 1', name='ck_pricing_strategy_name_min_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pricing_strategy_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('time_remaining_seconds', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.CheckConstraint('discount_percent >= 0 AND discount_percent <= 100', name='ck_pricing_strategy_step_discount_range'),
    sa.CheckConstraint('time_remaining_seconds >= 0', name='ck_pricing_strategy_step_time_remaining_positive'),
    sa.ForeignKeyConstraint(['strategy_id'], ['pricing_strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_strategy_steps_strategy_id'), 'pricing_strategy_steps', ['strategy_id'], unique=False)
    op.add_column('offers', sa.Column('pricing_strategy_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_offers_pricing_strategy_id'), 'offers', ['pricing_strategy_id'], unique=False)
    op.create_foreign_key(None, 'offers', 'pricing_strategies', ['pricing_strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offers', type_='foreignkey')
    op.drop_index(op.f('ix_offers_pricing_strategy_id'), table_name='offers')
    op.drop_column('offers', 'pricing_strategy_id')
    op.drop_index(op.f('ix_pricing_strategy_steps_strategy_id'), table_name='pricing_strategy_steps')
    op.drop_table('pricing_strategy_steps')
    op.drop_table('pricing_strategies')
    # ### end Alembic commands ###
