from datetime import datetime, timedelta, timezone
from typing import Dict, Any, Optional, TYPE_CHECKING
import jwt
import uuid
from config import settings

if TYPE_CHECKING:
    from app.auth.models import User


class JWTUtils:
    """Utilities for JWT token operations"""
    
    def __init__(self):
        self.secret_key = settings.jwt_secret_key
        self.algorithm = settings.jwt_algorithm
        self.access_token_expire_minutes = settings.jwt_access_token_expire_minutes
        self.refresh_token_expire_days = settings.jwt_refresh_token_expire_days
    
    def create_access_token(self, user: "User") -> str:
        """Create JWT access token"""
        payload = {
            "user_id": user.id,
            "email": user.email,
            "is_seller": user.is_seller,
            "type": "access",
            "exp": datetime.now() + timedelta(minutes=self.access_token_expire_minutes)
        }
        return jwt.encode(payload, self.secret_key, algorithm=self.algorithm)
    
    def create_refresh_token_string(self) -> str:
        """Create refresh token as UUID string (will be generated by DB)"""
        return str(uuid.uuid4())  # Fallback if needed
    
    def verify_access_token(self, token: str) -> Optional[Dict[str, Any]]:
        """Verify and decode JWT access token"""
        try:
            payload = jwt.decode(token, self.secret_key, algorithms=[self.algorithm])
            if payload.get("type") != "access":
                return None
            return payload
        except jwt.PyJWTError:
            return None
    
    def get_user_id_from_token(self, token: str) -> Optional[int]:
        """Extract user ID from access token"""
        payload = self.verify_access_token(token)
        return payload.get("user_id") if payload else None
