from typing import Optional
from datetime import datetime, timedelta, timezone
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, insert, update, delete
from app.auth.models import User, RefreshToken
from app.auth import schemas
from app.auth.password_utils import PasswordUtils


class AuthService:
    """Service for working with users in database"""
    
    def __init__(self):
        self.password_utils = PasswordUtils()
    
    async def create_user(
        self, 
        session: AsyncSession, 
        email: Optional[str] = None,
        phone: Optional[str] = None,
        password_hash: str = ""
    ) -> User:
        """Create a new user in database"""
        values = {"password_hash": password_hash}
        if email:
            values["email"] = email
        if phone:
            values["phone"] = phone
        
        result = await session.execute(
            insert(User).values(**values).returning(User)
        )
        return result.scalar_one()
    
    async def get_user(self, session: AsyncSession, user_id: int) -> Optional[User]:
        """Get user by ID"""
        result = await session.execute(
            select(User).where(User.id == user_id)
        )
        return result.scalar_one_or_none()
    
    async def get_user_by_email(self, session: AsyncSession, email: str) -> Optional[User]:
        """Get user by email"""
        result = await session.execute(
            select(User).where(User.email == email)
        )
        return result.scalar_one_or_none()
    
    async def get_user_by_phone(self, session: AsyncSession, phone: str) -> Optional[User]:
        """Get user by phone"""
        result = await session.execute(
            select(User).where(User.phone == phone)
        )
        return result.scalar_one_or_none()
    
    async def update_user_phone_verified(self, session: AsyncSession, user_id: int, phone_verified: bool) -> User:
        """Update user phone_verified field"""
        result = await session.execute(
            update(User).where(User.id == user_id).values(phone_verified=phone_verified).returning(User)
        )
        return result.scalar_one()
    
    async def verify_user_password(self, password: str, password_hash: str) -> bool:
        """Verify user password"""
        return self.password_utils.verify_password(password, password_hash)
    
    async def create_refresh_token(self, session: AsyncSession, user_id: int, expires_at: datetime) -> RefreshToken:
        """Create a new refresh token (UUID generated by DB)"""
        result = await session.execute(
            insert(RefreshToken).values(
                user_id=user_id,
                expires_at=expires_at,
                created_at=datetime.now()
            ).returning(RefreshToken)
        )
        return result.scalar_one()
    
    async def get_refresh_token(self, session: AsyncSession, token: str) -> Optional[RefreshToken]:
        """Get refresh token by token string"""
        result = await session.execute(
            select(RefreshToken).where(RefreshToken.token == token)
        )
        return result.scalar_one_or_none()
    
    async def revoke_refresh_token(self, session: AsyncSession, token: str) -> None:
        """Revoke refresh token"""
        await session.execute(
            update(RefreshToken)
            .where(RefreshToken.token == token)
            .values(is_revoked=True)
        )
    
    async def cleanup_expired_tokens(self, session: AsyncSession) -> None:
        """Clean up expired refresh tokens"""
        await session.execute(
            delete(RefreshToken).where(RefreshToken.expires_at < datetime.now())
        )

    async def update_user_is_seller(self, session: AsyncSession, user_id: int, is_seller: bool) -> User:
        """Update user is_seller field"""
        result = await session.execute(
            update(User).where(User.id == user_id).values(is_seller=is_seller).returning(User)
        )
        return result.scalar_one()
    
    async def delete_user(self, session: AsyncSession, user_id: int) -> bool:
        """Delete user by ID and all associated refresh tokens"""
        # Delete all refresh tokens for this user
        await session.execute(
            delete(RefreshToken).where(RefreshToken.user_id == user_id)
        )
        
        # Delete user
        result = await session.execute(
            delete(User).where(User.id == user_id)
        )
        return result.rowcount > 0
    
    async def update_user_firebase_token(self, session: AsyncSession, user_id: int, firebase_token: str) -> User:
        """Update user firebase_token field"""
        result = await session.execute(
            update(User).where(User.id == user_id).values(firebase_token=firebase_token).returning(User)
        )
        return result.scalar_one()
    
    async def get_user_firebase_token(self, session: AsyncSession, user_id: int) -> Optional[str]:
        """Get user firebase_token"""
        result = await session.execute(
            select(User.firebase_token).where(User.id == user_id)
        )
        return result.scalar_one_or_none()

    async def update_user_last_location(
        self, session: AsyncSession, user_id: int, latitude: float, longitude: float
    ) -> User:
        """Update user's last known location (latitude and longitude)"""
        result = await session.execute(
            update(User)
            .where(User.id == user_id)
            .values(last_latitude=latitude, last_longitude=longitude)
            .returning(User)
        )
        return result.scalar_one()